### ISSUE TITLE
Error message: index out of bounds: the len is 10833 but the index is 48737

### ISSUE THREAD

**Issue by jnalanko** [algbio/ggcat#10]
I get the error message below. The command is `ggcat build -c -k 31 -o coli3682.fna ~/data/coli3682_dataset/*`, where `~/data/coli3682_dataset` is this dataset: https://zenodo.org/record/6577997#.Y2TfEduxXRY

```
Allocator initialized: mem: 2 GiB chunks: 8192 log2: 18
Using m: 12 with k: 31
Started phase: reads bucketing prev stats: 
Elaborated 399801 sequences! [9978998363 | 99.74% qb] (1872[1878]/3682 => 50.84%)  ptime: 23.13s gtime: 23.14s
Temp buckets files size: 19.10 GiB
Finished phase: reads bucketing. phase duration: 43.75s gtime: 43.76s
Started phase: kmers merge prev stats: 
Found bucket with max size 269042 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145023 REAL_SIZE: 145027 SUB: 6
Found bucket with max size 190978 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 144964 REAL_SIZE: 144963 SUB: 5
Found bucket with max size 303654 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145561 REAL_SIZE: 145559 SUB: 8
Found bucket with max size 189907 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145192 REAL_SIZE: 145189 SUB: 4
Found bucket with max size 281469 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 146378 REAL_SIZE: 146375 SUB: 9
Found bucket with max size 191777 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 146586 REAL_SIZE: 146587 SUB: 1
Found bucket with max size 215135 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145356 REAL_SIZE: 145353 SUB: 7
Found bucket with max size 193783 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145767 REAL_SIZE: 145769 SUB: 0
Found bucket with max size 206533 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 145638 REAL_SIZE: 145641 SUB: 2
Found bucket with max size 326621 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 146576 REAL_SIZE: 146575 SUB: 10
Found bucket with max size 201093 ==> .temp_files/bucket.908 // EXPECTED_SIZE: 146539 REAL_SIZE: 146542 SUB: 3
Found bucket with max size 232594 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144757 REAL_SIZE: 144755 SUB: 5
Found bucket with max size 245208 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144758 REAL_SIZE: 144754 SUB: 4
Found bucket with max size 188785 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 145681 REAL_SIZE: 145683 SUB: 6
Found bucket with max size 513570 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144768 REAL_SIZE: 144775 SUB: 10
Found bucket with max size 277270 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144761 REAL_SIZE: 144755 SUB: 9
Found bucket with max size 244137 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 145985 REAL_SIZE: 145986 SUB: 2
Found bucket with max size 193494 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 146433 REAL_SIZE: 146430 SUB: 3
Found bucket with max size 230265 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 146471 REAL_SIZE: 146473 SUB: 1
Found bucket with max size 216359 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144868 REAL_SIZE: 144870 SUB: 7
Found bucket with max size 261307 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 144762 REAL_SIZE: 144761 SUB: 8
Found bucket with max size 168929 ==> .temp_files/bucket.944 // EXPECTED_SIZE: 145456 REAL_SIZE: 145458 SUB: 0
Found bucket with max size 233427 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 34206 REAL_SIZE: 34211 SUB: 11
Found bucket with max size 214098 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145090 REAL_SIZE: 145083 SUB: 2
Found bucket with max size 148920 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145070 REAL_SIZE: 145065 SUB: 0
Found bucket with max size 256156 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145669 REAL_SIZE: 145666 SUB: 7
Found bucket with max size 296412 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145240 REAL_SIZE: 145246 SUB: 5
Found bucket with max size 309196 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145990 REAL_SIZE: 145985 SUB: 9
Found bucket with max size 178942 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145848 REAL_SIZE: 145845 SUB: 1
Found bucket with max size 309570 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 146398 REAL_SIZE: 146411 SUB: 8
Found bucket with max size 383367 ==> .temp_files/bucket.406 // EXPECTED_SIZE: 145845 REAL_SIZE: 145844 SUB: 10
Found bucket with max size 244681 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 145666 REAL_SIZE: 145665 SUB: 2
Found bucket with max size 235229 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 145670 REAL_SIZE: 145673 SUB: 1
Found bucket with max size 246194 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 146113 REAL_SIZE: 146111 SUB: 5
Found bucket with max size 231931 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 146500 REAL_SIZE: 146504 SUB: 4
Found bucket with max size 249543 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 146225 REAL_SIZE: 146231 SUB: 8
Found bucket with max size 522478 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 145690 REAL_SIZE: 145685 SUB: 10
Found bucket with max size 187340 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 145673 REAL_SIZE: 145674 SUB: 3
Found bucket with max size 227460 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 146210 REAL_SIZE: 146207 SUB: 6
Found bucket with max size 185691 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 146549 REAL_SIZE: 146550 SUB: 0
Found bucket with max size 326026 ==> .temp_files/bucket.22 // EXPECTED_SIZE: 145681 REAL_SIZE: 145677 SUB: 9
Found bucket with max size 229211 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 29230 REAL_SIZE: 29217 SUB: 11
Found bucket with max size 176171 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145562 REAL_SIZE: 145558 SUB: 5
Found bucket with max size 262191 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145520 REAL_SIZE: 145523 SUB: 9
Found bucket with max size 174267 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 146001 REAL_SIZE: 146009 SUB: 1
Found bucket with max size 196214 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145751 REAL_SIZE: 145747 SUB: 4
Found bucket with max size 226865 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145803 REAL_SIZE: 145810 SUB: 6
Found bucket with max size 245701 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145962 REAL_SIZE: 145967 SUB: 8
Found bucket with max size 263075 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 146513 REAL_SIZE: 146516 SUB: 3
Found bucket with max size 243848 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 146003 REAL_SIZE: 146002 SUB: 0
Found bucket with max size 390354 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 145935 REAL_SIZE: 145934 SUB: 10
Found bucket with max size 161177 ==> .temp_files/bucket.10 // EXPECTED_SIZE: 146193 REAL_SIZE: 146190 SUB: 2
Found bucket with max size 183838 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 23173 REAL_SIZE: 23180 SUB: 11
Found bucket with max size 197540 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 145844 REAL_SIZE: 145840 SUB: 4
Found bucket with max size 285566 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 145843 REAL_SIZE: 145840 SUB: 8
Found bucket with max size 313293 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146192 REAL_SIZE: 146196 SUB: 9
Found bucket with max size 174097 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146123 REAL_SIZE: 146126 SUB: 6
Found bucket with max size 249186 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 145966 REAL_SIZE: 145965 SUB: 3
Found bucket with max size 182835 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146211 REAL_SIZE: 146248 SUB: 2
Found bucket with max size 277355 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146390 REAL_SIZE: 146326 SUB: 7
Found bucket with max size 244545 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146529 REAL_SIZE: 146534 SUB: 5
Found bucket with max size 166957 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146151 REAL_SIZE: 146150 SUB: 0
Found bucket with max size 418642 ==> .temp_files/bucket.112 // EXPECTED_SIZE: 146183 REAL_SIZE: 146200 SUB: 10

Thread panicked at location: /home/niklas/code/ggcat/pipeline/common/colors/src/managers/multiple.rs:312:37
Error message: index out of bounds: the len is 10833 but the index is 48737
Backtrace:    0: ggcat::main::{{closure}}
             at cmdline/src/main.rs:447:37
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/alloc/src/boxed.rs:2001:9
      std::panicking::rust_panic_with_hook
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/panicking.rs:65:14
   6: core::panicking::panic_bounds_check
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/panicking.rs:151:5
   7: <colors::managers::multiple::MultipleColorsManager<H,MH> as colors::colors_manager::ColorsMergeManager<H,MH>>::process_colors
   8: <kmers_merge::final_executor::ParallelKmersMergeFinalExecutor<H,MH,CX> as kmers_transform::KmersTransformFinalExecutor<kmers_merge::ParallelKmersMergeFactory<H,MH,CX>>>::process_map
             at pipeline/assembler/kmers_merge/src/final_executor.rs:193:13
   9: <kmers_transform::processor::KmersTransformProcessor<F> as parallel_processor::execution_manager::executor::AsyncExecutor>::async_executor_main::{{closure}}
             at pipeline/common/kmers_transform/src/processor.rs:113:26
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/future/mod.rs:91:19
      parallel_processor::execution_manager::thread_pool::ExecThreadPool::register_executors::{{closure}}::{{closure}}
             at libs/parallel-processor-rs/src/execution_manager/thread_pool.rs:78:25
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/future/mod.rs:91:19
      parallel_processor::execution_manager::thread_pool::ExecThreadPool::register_executors::{{closure}}
             at libs/parallel-processor-rs/src/execution_manager/thread_pool.rs:83:17
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/future/mod.rs:91:19
  10: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  11: tokio::runtime::task::raw::RawTask::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
      tokio::runtime::task::LocalNotified<S>::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
      tokio::coop::with_budget::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/thread/local.rs:446:16
      std::thread::local::LocalKey<T>::with
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/thread/local.rs:422:9
  12: tokio::coop::with_budget
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
      tokio::coop::budget
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  13: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:387:24
  14: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17
      tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  15: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5
  16: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21
      tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  17: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  18: tokio::runtime::task::raw::RawTask::poll
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
      tokio::runtime::task::UnownedTask<S>::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:422:9
      tokio::runtime::blocking::pool::Task::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:111:9
      tokio::runtime::blocking::pool::Inner::run
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:346:17
  19: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:321:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/sys_common/backtrace.rs:121:18
  20: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/thread/mod.rs:551:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/thread/mod.rs:550:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/core/src/ops/function.rs:251:5
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/alloc/src/boxed.rs:1987:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/alloc/src/boxed.rs:1987:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/bed4ad65bf7a1cef39e3d66b3670189581b3b073/library/std/src/sys/unix/thread.rs:108:17
  22: start_thread
             at /build/glibc-2ORdQG/glibc-2.27/nptl/pthread_create.c:463
  23: clone
             at /build/glibc-2ORdQG/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Guilucand** [comment]
The problem was caused by a missing normalization of sequences when they contained different letters than the canonical DNA letters. I've just pushed the fix.
